### ISSUE TITLE
Delivery profile option from drop down list not working, Give Uncaught SyntaxError: Unexpected token ,

### ISSUE THREAD

**Issue by blackyboy** [kaltura/platform-install-packages#333]
Hi @jessp01 @KalturaCommunity 

Hope you doing good,

Here is my issue, we using Kaltura Server 9.19.5 in production. Now we need to create a remote storage and rtmp streaming. Storage configured and working fine. while creating rtmp delivery using amazon cloud front as in before old version storage and delivery will be in same tab. But now it's separated as remote storage and delivery profile. While creating Storage profile it asked to choose delivery details in bottom as Delivery profile ids (JSON) in that if i add http it shows as default delivery profile with 500 ID, while choosing rtmp it too shows default profile with 201. 

![selection_001](https://cloud.githubusercontent.com/assets/4866182/5886887/d9983896-a3da-11e4-81d6-7df918c968dc.png)

Then back to create a delivery profile using http i get 502 as my ID and while creating rtmp it gives 503 ID, Did the above id in storage and this one need to match for get stream ? Now only my files are storing in amazon s3 i can't playback using cloud front. 

![selection_002](https://cloud.githubusercontent.com/assets/4866182/5886888/e337134a-a3da-11e4-91cd-69bdbb1a69ad.png)

while trying to edit the delivery profile which one already created i'am not getting the popup window. While clicking on Menu it getting choose but window not bringing up. So i have checked using inspect element from browser right click option and choose console while choosing any menu as Configure, Delete, or disable i'am getting this error "Uncaught SyntaxError: Unexpected token ,"

![selection_003](https://cloud.githubusercontent.com/assets/4866182/5886890/e926ada6-a3da-11e4-84a9-736e5d521f92.png)

Is there any fix for this? And how can i setup the delivery profile which match to storage profile which i have created from Amazon S3.

                                                                             Thank you...

**Comment by jessp01** [comment]
Hi @blackyboy.

Can you please paste the output for:
mysql>select * from delivery_profile\G
mysql>select * from storage_profile\G

Also, there is a script to help you configure remote and delivery profiles, see:
/opt/kaltura/bin/create_remote_storage.php
Might save a lot of time.

**Comment by blackyboy** [comment]
Hi @jessp01 

Thanks for you kind response, Here below is the result for query please have a note and guide me to get fix the issue. 

```
mysql> select * from delivery_profile\G
*************************** 1. row ***************************
             id: 501
     partner_id: 0
     created_at: 2014-11-26 22:27:26
     updated_at: 2014-11-26 22:27:26
           name: Default HTTP Delivery Profile
           type: 10
    system_name: Default Akamai HLS direct
    description: Default Akamai HLS direct
            url: http://media.xxxxxxxx.com:443
      host_name: media.xxxxxxxx.com
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp
     is_default: 1
      parent_id: 0
    custom_data: NULL
*************************** 2. row ***************************
             id: 500
     partner_id: 0
     created_at: 2014-11-26 22:27:26
     updated_at: 2014-11-26 22:27:26
           name: Default HTTP Delivery Profile
           type: 14
    system_name: Default HTTP Delivery Profile
    description: Default HTTP Delivery Profile
            url: http://media.xxxxxxxx.com:443
      host_name: media.xxxxxxxx.com
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: http
     is_default: 1
      parent_id: 0
    custom_data: NULL
*************************** 3. row ***************************
             id: 101
     partner_id: 0
     created_at: 2014-11-26 22:27:26
     updated_at: 2014-11-26 22:27:26
           name: Default HLS Live Delivery Profile
           type: 1001
    system_name: Default HLS Live Delivery Profile
    description: Default HLS Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp
     is_default: 1
      parent_id: 0
    custom_data: NULL
*************************** 4. row ***************************
             id: 1
     partner_id: 0
     created_at: 2014-11-26 22:27:26
     updated_at: 2014-11-26 22:27:26
           name: Default HD Network Live Delivery Profile
           type: 1002
    system_name: Default HD Network Live Delivery Profile
    description: Default HD Network Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: hdnetworkmanifest
     is_default: 1
      parent_id: 0
    custom_data: NULL
*************************** 5. row ***************************
             id: 2
     partner_id: 0
     created_at: 2014-11-26 22:27:26
     updated_at: 2014-11-26 22:27:26
           name: Default HDS Live Delivery Profile
           type: 1002
    system_name: Default HDS Live Delivery Profile
    description: Default HDS Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: hds
     is_default: 1
      parent_id: 0
    custom_data: NULL
*************************** 6. row ***************************
             id: 201
     partner_id: 0
     created_at: 2014-11-26 22:27:26
     updated_at: 2014-11-26 22:27:26
           name: Default RTMP Live Delivery Profile
           type: 1005
    system_name: Default RTMP Live Delivery Profile
    description: Default RTMP Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: rtmp
     is_default: 1
      parent_id: 0
    custom_data: a:1:{s:12:"enforceRtmpe";s:1:"0";}
*************************** 7. row ***************************
             id: 502
     partner_id: 107
     created_at: 2015-01-24 11:20:34
     updated_at: 2015-01-24 11:20:34
           name: Jigsaw RTMP
           type: 5
    system_name: NULL
    description: Jigsaw lms RTMP
            url: rtmp://shil9xxxxxxx.cloudfront.net/cfx/st
      host_name: shil9xxxxxxx.cloudfront.net
     recognizer: NULL
      tokenizer: NULL
         status: NULL
media_protocols: NULL
  streamer_type: rtmp
     is_default: 0
      parent_id: 0
    custom_data: a:2:{s:12:"enforceRtmpe";b:0;s:6:"prefix";s:8:"/kaltura";}
*************************** 8. row ***************************
             id: 503
     partner_id: 107
     created_at: 2015-01-24 11:38:22
     updated_at: 2015-01-24 11:38:22
           name: Jigsaw HTTP
           type: 4
    system_name: NULL
    description: Jigsaw lms HTTP
            url: http://d1sw1xxxxxxxd.cloudfront.net/kaltura
      host_name: d1sw1xxxxxxd.cloudfront.net
     recognizer: NULL
      tokenizer: NULL
         status: NULL
media_protocols: NULL
  streamer_type: http
     is_default: 0
      parent_id: 0
    custom_data: NULL
*************************** 9. row ***************************
             id: 504
     partner_id: 107
     created_at: 2015-01-24 12:01:59
     updated_at: 2015-01-24 12:01:59
           name: Jigsaw HTTP1
           type: 4
    system_name: NULL
    description: NULL
            url: http://d1sw19xxxxxx.cloudfront.net/kaltura
      host_name: d1sw19xxxxxxx.cloudfront.net
     recognizer: NULL
      tokenizer: NULL
         status: NULL
media_protocols: NULL
  streamer_type: auto
     is_default: 0
      parent_id: 0
    custom_data: NULL
9 rows in set (0.00 sec)
```

Second Query select * from storage_profile\G


```
mysql> select * from storage_profile\G
*************************** 1. row ***************************
                        id: 0
                created_at: 2014-11-26 22:27:25
                updated_at: 2014-11-26 22:27:25
                partner_id: 0
                      name: dc
               system_name: 
                desciption: data center
                    status: 3
                  protocol: 0
               storage_url: /opt/kaltura/web
          storage_base_dir: NULL
          storage_username: NULL
          storage_password: NULL
  storage_ftp_passive_mode: NULL
    delivery_http_base_url: NULL
     delivery_rmp_base_url: NULL
     delivery_iis_base_url: NULL
             min_file_size: NULL
             max_file_size: NULL
         flavor_params_ids: NULL
max_concurrent_connections: NULL
               custom_data: NULL
        path_manager_class: NULL
         url_manager_class: 
         delivery_priority: 1
           delivery_status: 1
*************************** 2. row ***************************
                        id: 2
                created_at: 2015-01-24 11:02:05
                updated_at: 2015-01-24 12:12:06
                partner_id: 107
                      name: jxxxxxxx
               system_name: 
                desciption: 
                    status: 2
                  protocol: 6
               storage_url: http://xxxxxx-kaltura.s3.amazonaws.com
          storage_base_dir: /xxxxxx-kaltura/kaltura
          storage_username: AKxIAxxxxxxxxxxxxxxxxx
          storage_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCiC/
  storage_ftp_passive_mode: 0
    delivery_http_base_url: NULL
     delivery_rmp_base_url: NULL
     delivery_iis_base_url: NULL
             min_file_size: 0
             max_file_size: 0
         flavor_params_ids: 
max_concurrent_connections: NULL
               custom_data: a:6:{s:7:"trigger";i:3;s:14:"ready_behavior";i:0;s:17:"allow_auto_delete";b:0;s:20:"delivery_profile_ids";a:2:{s:4:"http";a:1:{i:0;i:500;}s:4:"rtmp";a:1:{i:0;i:201;}}s:22:"files_permission_in_s3";s:11:"public-read";s:19:"path_manager_params";s:6:"a:0:{}";}
        path_manager_class: kPathManager
         url_manager_class: 
         delivery_priority: 0
           delivery_status: 1
2 rows in set (0.02 sec)
```

I have looked into the script /opt/kaltura/bin/create_remote_storage.php but i don't have idea how to use this script any idea about how to do it ? 

                            Thanks..
